deployment:
  toSsh:
    enabled: false
    host: 192.168.56.11
    user: stefanwalther
    password: Test1234
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/sense-funnel-chart"
